RepPortal/Models/Store.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RepPortal.Models
{
    public class Store
    {
        [Key]
        public int StoreId { get; set; }

        [Required]
        [ForeignKey("UserId")]
        public ApplicationUser User { get; set; }

        [ForeignKey("SalesRepId")]
        [Display(Name="Sales Rep")]
        public ApplicationUser SalesRep { get; set; }

        [Required]
        [Display(Name="Store Name")]
        [StringLength(50, ErrorMessage = "Please shorten Store Name.")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Store Street Address")]
        [StringLength(60, ErrorMessage = "Please shorten Street Address to less than 60 characters.")]
        public string StreetAddress { get; set; }

        [Required]
        [Display(Name = "City")]
        [StringLength(40, ErrorMessage = "Please shorten City name to less than 40 characters.")]
        public string City { get; set; }

        [Required]
        [Display(Name = "State")]
        public int StateId { get; set; }

        public State State { get; set; }

        [Required]
        [StringLength(10, ErrorMessage = "Too many characters.")]
        public string Zipcode { get; set; }

        [Display(Name = "Phone Number")]
        [StringLength(12, ErrorMessage = "Make sure format is 111-111-1111")]
        public string PhoneNumber { get; set; }
        
        [Display(Name = "Website")]
        [StringLength(100, ErrorMessage = "The website URL is too long.")]
        public string WebsiteURL { get; set; }

        [Display(Name = "Store Email")]
        [StringLength(100, ErrorMessage = "The email address is too long.")]
        public string Email { get; set; }

        [Display(Name = "Store Contact Name")]
        public string ContactName { get; set; }

        [DataType(DataType.Date)]
        public DateTime? DateAdded { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime DateCreated { get; set; }

        //[Range(1, int.MaxValue, ErrorMessage = "Please select a status from list.")]
        public int StatusId { get; set; }

        public Status Status { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date Store Closed")]
        public DateTime? DateClosed { get; set; }

        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Last Order Total")]
        public double? LastOrderTotal { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Last Order Date")]
        public DateTime? LastOrderDate { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Last Order Ship Date")]
        public DateTime? LastOrderShipDate { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Last Order Paid Date")]
        public DateTime? LastOrderPaidDate { get; set; }

        
        public string Lat { get; set; }
        
        public string Long { get; set; }


        public virtual ICollection<StoreFlag> StoreFlags { get; set; }
        public virtual ICollection<StoreNote> StoreNotes { get; set; }

    }
}

RepPortal/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RepPortal.Data;
using RepPortal.Models;
using RepPortal.Models.StoreViewModels;
using CsvHelper.Configuration;
using System.Text.RegularExpressions;
using System.Net.Http;
using System.Net.Http.Headers;
using Microsoft.Extensions.Configuration;
using System.Net;
using System.Xml.Linq;

namespace RepPortal.Controllers
{
    public class StoresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _iConfiguration;

        public StoresController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IConfiguration iConfiguration)
        {
            _userManager = userManager;
            _context = context;
            _iConfiguration = iConfiguration;
        }

        // This task retrieves the currently authenticated user
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Stores
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            // get current user
            ApplicationUser user = await GetCurrentUserAsync();

            // Get the roles for the user
            var roles = await _userManager.GetRolesAsync(user);

            // create a list of stores
            // by default, only retrieve matching stores where current user is the Sales Rep attached to the store
            var stores = _context.Store.Include("SalesRep").Include("State").Include("Status").Where(s => s.SalesRep == user);

            // check if the user is an Administrator
            if (roles.Contains("Administrator"))
            {
                // retrieve all stores to display (for site administrator)
                stores = _context.Store.Include("SalesRep").Include("State").Include("Status");
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                stores = stores.Where(s => s.Name.ToLower().Contains(searchString.ToLower()) || s.Status.Name.ToLower().Contains(searchString.ToLower()));
            }

            ViewData["CurrentSort"] = sortOrder;
            ViewData["OrderDateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Date" : "";
            ViewData["NameSortParm"] = sortOrder == "name" ? "name_desc" : "Name";
            ViewData["StatusSortParm"] = sortOrder == "Status" ? "status_desc" : "Status";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            switch (sortOrder)
            {
                case "Name":
                    stores = stores.OrderBy(s => s.Name);
                    break;
                case "name_desc":
                    stores = stores.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    stores = stores.OrderBy(s => s.LastOrderDate);
                    break;
                case "date_desc":
                    stores = stores.OrderByDescending(s => s.LastOrderDate);
                    break;
                case "Status":
                    stores = stores.OrderBy(s => s.StatusId);
                    break;
                case "status_desc":
                    stores = stores.OrderByDescending(s => s.StatusId);
                    break;
                default:
                    stores = stores.OrderByDescending(s => s.LastOrderDate);
                    break;
            }

            // set amount of stores to display per page
            int pageSize = 25;
            return View(await PaginatedList<Store>.CreateAsync(stores, page ?? 1, pageSize));

        }

        // GET: Stores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            // create a new view model instance
            StoreDetailViewModel sdvm = new StoreDetailViewModel();

            // find any flags for the store
            var flag = await _context.StoreFlag.Include("Flag").Where(f => f.StoreId == id).SingleOrDefaultAsync();
            // attach flag info to the view model
            sdvm.Flag1 = flag;

            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Store
                .Include(s => s.SalesRep)
                .Include(s => s.State)
                .Include(s => s.Status)
                .SingleOrDefaultAsync(m => m.StoreId == id);
            if (store == null)
            {
                return NotFound();
            }

            // attach the store to the view model
            sdvm.Store = store;

            // return the view model
            return View(sdvm);
        }

        // GET: Stores/Create
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create()
        {
            CreateStoreViewModel createStoreViewModel = new CreateStoreViewModel();
            createStoreViewModel.Store = new Store();
            // set the store status to 1 for new stores. The input field is hidden for this. Site will control this status based on the store's Last Order. 
            createStoreViewModel.Store.StatusId = 1;

            ViewBag.SalesReps = _context.Users.OrderBy(u => u.FirstName)
                .Select(u => new SelectListItem() { Text = $"{ u.FirstName} { u.LastName}", Value = u.Id }).ToList();

            ViewData["StateId"] = new SelectList(_context.State.OrderBy(s => s.Name), "StateId", "Name");
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "Name");

            return View(createStoreViewModel);
        }

        // POST: Stores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create(CreateStoreViewModel storeModel)
        {
            ModelState.Remove("store.user");


            if (ModelState.IsValid)
            {
                // Get the current user
                ApplicationUser user = await GetCurrentUserAsync();

                if (storeModel.SalesRepId != null)
                {
                    // find matching user for SalesRep in system
                    ApplicationUser SalesRep = _context.Users.Single(u => u.Id == storeModel.SalesRepId);

                    // store the sales rep on the store
                    storeModel.Store.SalesRep = SalesRep;
                }

                // Add current user to store listing
                storeModel.Store.User = user;

                // Add a creation date
                storeModel.Store.DateCreated = DateTime.Now;

                // save store to context
                _context.Add(storeModel.Store);
                // save context file to database
                await _context.SaveChangesAsync();
                // redirect user to list of all stores
                return RedirectToAction(nameof(Index));
            }

            CreateStoreViewModel createStoreViewModel = new CreateStoreViewModel();
            // get current user
            var CurrentUser = await GetCurrentUserAsync();
            // populate SaleReps dropdown list by retrieving all users that are not the current user. 
            // Only administrator will be allowed to create a new store listing, so they will be current User.
            ViewBag.SalesReps = _context.Users.OrderBy(u => u.FirstName)
                .Select(u => new SelectListItem() { Text = u.FirstName, Value = u.Id }).ToList();
            ViewData["StateId"] = new SelectList(_context.State, "StateId", "Name", storeModel.Store.StateId);
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "Color", storeModel.Store.StatusId);

            return View(createStoreViewModel);
        }

        // GET: Stores/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Store.Include("User").Include("SalesRep").Include("State").Include("Status").SingleOrDefaultAsync(m => m.StoreId == id);
            if (store == null)
            {
                return NotFound();
            }

            CreateStoreViewModel createStoreViewModel = new CreateStoreViewModel();
            if (store.SalesRep != null)
            {
                createStoreViewModel.SalesRepId = store.SalesRep.Id;
            }
            else
            {
                createStoreViewModel.SalesRepId = null;
            }
            createStoreViewModel.Store = store;

            ViewBag.SalesReps = _context.Users.OrderBy(u => u.FirstName).Select(u => new SelectListItem() { Text = $"{ u.FirstName} { u.LastName}", Value = u.Id }).ToList();

            ViewData["StateId"] = new SelectList(_context.State.OrderBy(s => s.Name), "StateId", "Name", store.StateId);

RepPortal/ViewComponents/StoreNotesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RepPortal.Data;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using RepPortal.Models;
using RepPortal.Models.StoreNotesViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RepPortal.ViewComponents
{
    public class StoreNotesViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public StoreNotesViewComponent(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // This task retrieves the currently authenticated user
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IViewComponentResult> InvokeAsync(int storeId)
        {
            var user = await GetCurrentUserAsync();

            // create a new StoreNoteViewModel
            StoreNoteViewModel snvm = new StoreNoteViewModel()
            {
                // attach the current store id to the view model, to use to attach to a new store note when one is created
                CurrentStoreId = storeId,
                CurrentUser = user
            };

            // get StoreNotes from the database for the current store being viewed
            snvm.AllNotesForStore = await _context.StoreNote.Include("User").Include(sn => sn.Store).Where(sn => sn.Store.StoreId == storeId).OrderBy(sn => sn.DateCreated).ToListAsync();
                       
            // return notes
            return View(snvm);
        }

    }
}

RepPortal/Views/Stores/Details.cshtml
@model RepPortal.Models.StoreViewModels.StoreDetailViewModel

@{
    ViewData["Title"] = "Store Details";
}

<h2>
    <a asp-action="Index" class=""><span class="glyphicon glyphicon-chevron-left back-arrow" aria-hidden="true" data-toggle="tooltip" title="Back to Stores list"></span></a>
    Store Details
</h2>

<hr />
<div class="row">
    <div class="col-sm-12 col-md-7">
        @if (Model.Flag1 == null)
        {
            <p>
                <button class="btn btn-info" type="button" id="addressSearch"
                        onclick="location.href='@Url.Action("AddFlag", "Stores", new { id = Model.Store.StoreId })'" data-toggle="tooltip" title="Click to add reminder">
                    Follow Up?
                </button>
                
            </p>
        }
        <div class="store-details__Name">
            <h3>
                @Html.DisplayFor(model => model.Store.Name)

                @if (Model.Flag1 != null)
                {
                    <img src="~/images/flag.svg" alt="Follow Up" class="img-responsive inline" width="25" data-toggle="tooltip" title="Follow Up!" />
                }
            </h3>
        </div>

        <dl class="dl-horizontal white-background rounded store-details">
            <dt>
                @Html.DisplayNameFor(model => model.Store.Status)
            </dt>
            <dd>
                <img src='@string.Format("/images/map-icons/Shopping_Bag_{0}.svg", Model.Store.StatusId)' data-toggle="tooltip" title="@Model.Store.Status.Name" />
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.StreetAddress)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.StreetAddress)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.City)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.City)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.State)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.State.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.Zipcode)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.Zipcode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.PhoneNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.PhoneNumber)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.Email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.WebsiteURL)
            </dt>
            <dd>
                <a href="@Html.DisplayFor(model => model.Store.WebsiteURL)" target="_blank">@Html.DisplayFor(model => model.Store.WebsiteURL)</a>
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.ContactName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.ContactName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.SalesRep)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.SalesRep.FirstName) @Html.DisplayFor(model => model.Store.SalesRep.LastName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.DateAdded)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.DateAdded)
            </dd>
            @if (@Model.Store.StatusId == 4)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Store.DateClosed)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Store.DateClosed)
                </dd>
            }
            <dt>
                @Html.DisplayNameFor(model => model.Store.LastOrderTotal)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.LastOrderTotal)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.LastOrderDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.LastOrderDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.LastOrderShipDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.LastOrderShipDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Store.LastOrderPaidDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Store.LastOrderPaidDate)
            </dd>
        </dl>

        @if (User.IsInRole("Administrator"))
        {
        <div class="col-md-7">

            <a asp-action="Edit" asp-route-id="@Model.Store.StoreId" class="btn btn-default">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                <span class="edit-btn-text">Edit</span>
            </a>
            <a asp-action="Delete" asp-route-id="@Model.Store.StoreId" class="btn btn-warning">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                <span class="delete-btn-text">Delete</span>
            </a>
        </div>
        }


    </div>
    <div class="col-md-5 store-notes">
        @await Component.InvokeAsync("StoreNotes", new { storeId = Model.Store.StoreId })
    </div>
</div>


RepPortal/Views/Stores/Index.cshtml
@model PaginatedList<RepPortal.Models.Store>

@{
    ViewData["Title"] = "Stores In Your Territory";
}

<h2>Stores In Your Territory</h2>

<div class="row white-background store-list rounded">
    @if (User.IsInRole("Administrator"))
    {
        <div class="col-md-5">
            <div class="row">
                <button class="btn btn-info" type="button" id="addressSearch"
                        onclick="location.href='@Url.Action("Create", "Stores")'">
                    Add A Store
                </button>
            </div>
            <br />
            <div class="row">
                <button class="btn btn-warning" type="button" id="addressSearch"
                        onclick="location.href='@Url.Action("GeolocateAllStores", "Stores")'">
                    Geolocate All Stores
                </button>
            </div>
        </div>

        <div class="col-md-7">

            @using (Html.BeginForm("UpdateStoreViaCsv", "Stores", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <label for="attachmentUpdateCsv">Update Store Sales Data via CSV File</label>
                    <label class="btn btn-default btn-file">
                        <input type="file" name="attachmentUpdateCsv" id="attachmentUpdateCsv" hidden>
                    </label>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
                
            }

            @using (Html.BeginForm("AddStoresViaCsv", "Stores", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <label for="attachment">Add stores via CSV File</label>
                    <label class="btn btn-default btn-file">
                        <input type="file" name="attachmentcsv" id="attachmentcsv" hidden>
                    </label>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            }
        </div>
    }

    <form asp-action="Index" method="get">
        <div class="form-actions no-color">

            <label for="SearchString">Search by Name or Status:</label>
            <div class="row">
                <span class="form-group col-sm-4">
                    <input type="text" class="form-control" id="SearchString "name="SearchString" value="@ViewData["currentFilter"]" />
                </span>
                <input type="submit" value="Search" class="btn btn-info" /> 
                <a asp-action="Index" class="btn btn-default">Clear Search</a>

            </div>

        </div>
    </form>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["StatusSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Status</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Name</a>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().StreetAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().WebsiteURL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().ContactName)
                </th>
                @if (User.IsInRole("Administrator"))
                {
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().SalesRep)
                    </th>
                }
                @if (@Html.DisplayNameFor(model => model.FirstOrDefault().Status) == "Closed")
                {
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().DateClosed)
                    </th>
                }
                <th>Notes</th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["OrderDateSortParm"]">@Html.DisplayNameFor(model => model.FirstOrDefault().LastOrderDate)</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        <img src='@string.Format("/images/map-icons/Shopping_Bag_{0}.svg", item.StatusId)' data-toggle="tooltip" title="@item.Status.Name" data-placement="left" />
                       
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <div>@Html.DisplayFor(modelItem => item.StreetAddress)</div>

                        <div>
                            @Html.DisplayFor(modelItem => item.City)
                            @Html.DisplayFor(modelItem => item.State.Name)
                            @Html.DisplayFor(modelItem => item.Zipcode)
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        <a href="@Html.DisplayFor(modelItem => item.WebsiteURL)" target="_blank">@Html.DisplayFor(modelItem => item.WebsiteURL)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContactName)
                    </td>
                    @if (User.IsInRole("Administrator"))
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.SalesRep.FirstName) @Html.DisplayFor(modelItem => item.SalesRep.LastName)
                        </td>
                    }
                    @if (@Html.DisplayNameFor(model => model.FirstOrDefault().Status) == "Closed")
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.DateClosed)
                        </td>
                    }
                        <td>
                            
                            <a asp-action="Details" asp-route-id="@item.StoreId" data-toggle="tooltip" title="See Notes"><img src="~/images/creative-process.svg" alt="See Store Notes" class="img-responsive inline" width="25" /></a>
                        </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastOrderDate)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.StoreId">Details</a>
                        @if (User.IsInRole("Administrator"))
                        {
                           <text> | </text> <a asp-action="Edit" asp-route-id="@item.StoreId">Edit</a><text> | </text>
                            <a asp-action="Delete" asp-route-id="@item.StoreId">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>

</div>