RepPortal/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RepPortal.Models
{
    public class Note
    {
        [Key]
        public int NoteId { get; set; }

        [Required]
        [ForeignKey("UserId")]
        public ApplicationUser User { get; set; }

        [Display(Name = "To User")]
        [ForeignKey("ToUserId")]
        public ApplicationUser ToUser { get; set; }

        [Required]
        [Display(Name = "Note")]
        public string Content { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DateCreated { get; set; }

    }
}

RepPortal/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RepPortal.Data;
using RepPortal.Models;
using RepPortal.Models.NotesViewModels;

namespace RepPortal.Controllers
{
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public NotesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // This task retrieves the currently authenticated user
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            var notes = await _context.Note.Include("ToUser").ToListAsync();

            return View(notes);
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .SingleOrDefaultAsync(m => m.NoteId == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // GET: Notes/Create
        public IActionResult Create()
        {
            CreateNoteViewModel CreateNoteViewModel = new CreateNoteViewModel();

            ViewBag.Users = _context.Users.OrderBy(u => u.FirstName)
                .Select(u => new SelectListItem() { Text = $"{ u.FirstName} { u.LastName}", Value = u.Id }).ToList();


            return View(CreateNoteViewModel);
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( CreateNoteViewModel noteViewModel)
        {
            ModelState.Remove("note.user");

            if (ModelState.IsValid)
            {
                if (noteViewModel.ToUserId != null)
                {
                    // find matching user for SalesRep in system
                    ApplicationUser ToUser = _context.Users.Single(u => u.Id == noteViewModel.ToUserId);

                    // store the sales rep on the store
                    noteViewModel.Note.ToUser = ToUser;
                }

                // get current user
                ApplicationUser user = await GetCurrentUserAsync();
                // add current user
                noteViewModel.Note.User = user;

                _context.Add(noteViewModel.Note);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index", "Home");
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note.Include("ToUser").SingleOrDefaultAsync(m => m.NoteId == id);
            // create a new view model and attach the retrieved note
            var cnvm = new CreateNoteViewModel()
            {
                Note = note
            };

            if (note.ToUser != null)
            {
                cnvm.ToUserId = note.ToUser.Id;
            }
            else
            {
                cnvm.ToUserId = null;
            }

            // populate dropdown of users
            ViewBag.Users = _context.Users.OrderBy(u => u.FirstName)
                .Select(u => new SelectListItem() { Text = $"{ u.FirstName} { u.LastName}", Value = u.Id }).ToList();

            if (note == null)
            {
                return NotFound();
            }
            return View(cnvm);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateNoteViewModel noteViewModel)
        {
            if (id != noteViewModel.Note.NoteId)
            {
                return NotFound();
            }

            // remove user from model state
            ModelState.Remove("note.User");

            if (ModelState.IsValid)
            {
                // attach the user object for the user that was selected as the recipient 
                noteViewModel.Note.ToUser = await _context.Users.SingleOrDefaultAsync(u => u.Id == noteViewModel.ToUserId);

                try
                {
                    _context.Update(noteViewModel.Note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(noteViewModel.Note.NoteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(noteViewModel.Note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note.Include("ToUser")
                .SingleOrDefaultAsync(m => m.NoteId == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var note = await _context.Note.SingleOrDefaultAsync(m => m.NoteId == id);
            _context.Note.Remove(note);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool NoteExists(int id)
        {
            return _context.Note.Any(e => e.NoteId == id);
        }
    }
}

RepPortal/Views/Shared/Components/Notes/Default.cshtml
@model RepPortal.Models.NotesViewModels.CreateNoteViewModel


<h4>Notes:</h4>

<div id="notes" class="notes rounded white-background">
    @foreach (Note n in Model.UserNotes)
    {
        <div class="note" id=@n.NoteId>
            <div class="note__author-Date">
                <span class="note__author">@n.User.FirstName @n.User.LastName</span>
                <span class="note__date">@n.DateCreated</span>
                @if (Model.CurrentUser.Id == n.User.Id)
                {
                    <span class="pull-right">
                        <a asp-controller="Notes" asp-action="Edit" asp-route-id="@n.NoteId" data-toggle="tooltip" title="Edit"><span class="note__edit glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                        <a asp-controller="Notes" asp-action="Delete" asp-route-id="@n.NoteId" data-toggle="tooltip" title="Delete"><span class="note__delete glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    </span>
                }
            </div>
            @if (User.IsInRole("Administrator") && n.ToUser != null)
            {
                <div class="note__recepient"><span class="bold">To:</span> @n.ToUser.FirstName  @n.ToUser.LastName</div>
            }
            <div class="note__content"><span>@n.Content</span></div>
            <hr />
        </div>
    }
</div>


<form asp-controller="notes" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <h4>Add a Note</h4>
    @if (User.IsInRole("Administrator"))
    {
        <div class="form-group">
            @Html.DropDownListFor(model => model.ToUserId,
                                           ViewBag.Users as IEnumerable<SelectListItem>, "Select Recipient", new { @class = "form-control" })
        </div>
    }
    <div class="form-group">

        <textarea asp-for="@Model.Note.Content" rows="5" class="form-control" placeholder="Enter content here... "></textarea>
        <span asp-validation-for="@Model.Note.Content" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save Note" class="btn btn-default" />
    </div>
</form>
